name: Run Pytest with HTML Report

on:
  push:
    branches: [main]  # Trigger only on push to main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-playwright pytest-html
          playwright install --with-deps chromium

      - name: List files for debugging
        run: ls -R  # Show repo structure

      - name: Run pytest with HTML report
        run: pytest Playwright/test_playw_test_1.py --html=reports/pytest-report-${{ github.run_id }}.html --self-contained-html --verbose

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ github.run_id }}
          path: reports/pytest-report-${{ github.run_id }}.html
          retention-days: 30