name: Run Pytest

on:
  push:           # ✅ Trigger on push to ANY branch
  pull_request:   # ✅ Also run tests on pull requests (optional but good practice)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Show project structure (for debugging)
        run: ls -R

      - name: Run pytest
        run: pytest --verbose